# Generated by Django 5.0.6 on 2024-06-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lacality',
            new_name='locality',
        ),
    ]
